---
title: "Advanced ggplotting"
author: "Jenner Smith"
date: "2024-04-17"
output: html_document
---
I want to work on my map-making skills in R using ggplot. 
followed a tutorial to develop my own map using this link using this link: https://r-spatial.org/r/2018/10/25/ggplot2-sf.html

Library Calls
```{r}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
```

Create Daataset

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
```

Create Simple World Map

```{r}
ggplot(data = world) +
  geom_sf()
```

Adding Axis Labels & Title 

```{r}
ggplot(data = world) +
  geom_sf() +
  xlab("Longitude") + ylab("Latitude") +
  ggtitle("World map")
```

Experimenting with Different Colors 

```{R}
ggplot(data = world) + 
  geom_sf(color = "black", fill = "lightgreen")

ggplot(data = world) +
  geom_sf(aes(fill = pop_est)) +
  scale_fill_viridis_c(option = "plasma", trans = "sqrt")
                 
ggplot(data = world) +
  geom_sf(aes(fill = gdp_md)) +
  scale_fill_viridis_c(option = "cividis", trans = "sqrt")
```

Playing Around with Map Extent 

```{R}
# florida keys

ggplot(data = world) +
  geom_sf() +
  coord_sf(xlim = c(-102.15, -74.12), ylim = c(7.65, 33.97), expand = FALSE)

#chesapeake bay 

ggplot(data = world) +
  geom_sf() +
  coord_sf(xlim = c(-78,-74), ylim = c(36.5,40), expand = FALSE)

#puget sound  

ggplot(data = world) +
  geom_sf() +
  coord_sf(xlim = c(-124,-122), ylim = c(47,49), expand = FALSE)

# "study area"
ggplot(data = world) +
  geom_sf() +
  coord_sf(xlim = c(100,150), ylim = c(-20,20), expand = FALSE)
```

Adding Geographic Labels

```{R}

world_points<- st_centroid(world) # create data layer of country names 
world_points <- cbind(world, st_coordinates(st_centroid(world$geometry))) # link names with respective geographic data

ggplot(data = world) +
  geom_sf() +
  geom_text(data= world_points,aes(x=X, y=Y, label=name),
            color = "black", fontface = "bold", check_overlap = FALSE, size=2.5) +
  coord_sf(xlim = c(100,150), ylim = c(-20,20), expand = FALSE)
```

Creating the Final Map

```{R}
ggplot(data = world) +
  geom_sf(aes(fill = pop_est)) +
  scale_fill_viridis_c(option = "plasma", trans = "sqrt") +
  geom_text(data= world_points,aes(x=X, y=Y, label=name),
            color = "grey10", fontface = "bold", check_overlap = FALSE, size=2.5) +
  coord_sf(xlim = c(100,150), ylim = c(-20,20), expand = FALSE) +
  xlab('Longitude') + ylab('Latitude') + 
  ggtitle('Population of Oceania') +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "bl", which_north = "true",
                         pad_x = unit(0.75, "in"), pad_y = unit(0.25, "in"),
                         style = north_arrow_fancy_orienteering) 
```